config = {
    'scheduler': 'slurm',
    'extra_args': ['--mail-user=mahpe@dtu.dk', '--mail-type=NONE'],
    'mpiexec': '',
    'nodes': [
            ('xeon56', {'queue': 'slurm',
                        'cores': 56,
                        'memory': '500G'}),
            ('xeon24el8', {'queue': 'slurm',
                        'cores': 24,
                        'memory': '250G'}),
             ('xeon40el8', {'queue': 'slurm',
                        'cores': 40,
                        'memory': '384G'}),
            ('xeon24el8', {'queue': 'slurm',
                        'cores': 24,
                        'memory': '250G'}),
            ('xeon16', {'queue': 'slurm',
                        'cores': 16,
                        'memory': '60G'}),
            ('epyc96',  {'queue': 'slurm',
                        'cores': 96,
                        'memory': '768G'}),
            ('xeon24_512', {'queue': 'slurm',
                            'cores': 24,
                            'memory': '500G',}),
            ('xeon24el8_test', {'queue': 'slurm',
                            'cores': 24,
                            'memory': '500G',}),
            ('xeon40_768', {'queue': 'slurm',
                            'cores': 40,
                            'memory': '750G'}),
            ('sm3090el8', {'queue': 'slurm',
                        'cores': 8,
                        'memory': '191G',
                        'extra_args': ['--gres=gpu:RTX3090:1','--export=ALL,MKL_NUM_THREADS=1,NUMEXPR_NUM_THREADS=1,OMP_NUM_THREADS=1,OPENBLAS_NUM_THREADS=1']}),
            ('sm3090_devel', {'queue': 'slurm',
                        'cores': 8,
                        'memory': '191G',
                        'extra_args': ['--gres=gpu:RTX3090:1','--export=ALL,MKL_NUM_THREADS=1,NUMEXPR_NUM_THREADS=1,OMP_NUM_THREADS=1,OPENBLAS_NUM_THREADS=1']}),            
            ('sm3090el8_768', {'queue': 'slurm',
                        'cores': 8,
                        'memory': '191G',
                        'extra_args': ['--gres=gpu:RTX3090:1','--export=ALL,MKL_NUM_THREADS=1,NUMEXPR_NUM_THREADS=1,OMP_NUM_THREADS=1,OPENBLAS_NUM_THREADS=1']}),
            ('a100', {'queue': 'slurm',
                            'cores': 32,
                            'memory': '512000M',
                            'extra_args': ['--gres=gpu:A100:1']})
    ],
    'maximum_diskspace': 4
}
